# New ports collection makefile for:	php52-pdo_sqlite
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/databases/php52-pdo_sqlite/Makefile,v 1.1 2010/04/23 16:30:34 dinoex Exp $
#

CATEGORIES=	databases

MASTERDIR=      ${.CURDIR}/../php52-pfsense

PKGNAMESUFFIX=	-pdo_sqlite

.include "${MASTERDIR}/Makefile"
