# New ports collection makefile for:	php4-shmop
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/devel/php4-shmop/Makefile,v 1.1 2004/07/19 08:02:02 ale Exp $
#

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php4

PKGNAMESUFFIX=	-shmop

.include "${MASTERDIR}/Makefile"
