# New ports collection makefile for:	php5-posix
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/sysutils/php5-posix/Makefile,v 1.4 2007/11/14 07:38:32 ale Exp $
#

CATEGORIES=	sysutils

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-posix

.include "${MASTERDIR}/Makefile"
