# New ports collection makefile for:	php4-sysvmsg
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/devel/php4-sysvmsg/Makefile,v 1.1 2004/07/19 08:02:28 ale Exp $
#

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php4

PKGNAMESUFFIX=	-sysvmsg

.include "${MASTERDIR}/Makefile"
