#!/bin/sh

#set -e

if [ ! -d "/usr/ports" ]; then
	portsnap fetch
	portsnap extract
fi

# Add cpdup
if [ ! -f "/usr/local/bin/cpdup" ]; then
	echo "Cannot find cpdup, building from ports..."
	(cd /usr/ports/sysutils/cpdup/ && make deinstall clean)
	(cd /usr/ports/sysutils/cpdup/ && make ${MAKEJ_PORTS} BATCH=yo)
	(cd /usr/ports/sysutils/cpdup/ && make  install FORCE_PKG_REGISTER=yo BATCH=yo)	
	if [ ! -f "/usr/local/bin/cpdup" ]; then
		echo "Something went wrong while attempting installation of cpdup."
		exit 1
	fi
fi

CURRENTDIR=`pwd`
[ -r "${CURRENTDIR}/pfsense_local.sh" ] && . ${CURRENTDIR}/pfsense_local.sh

# Update BSDInstaller
echo "Updating BSDInstaller collection..."
/usr/bin/csup ${CURRENTDIR}/bsdinstaller-supfile

mkdir -p ${BASE_DIR}/installer
ln -s ${BUILDER_TOOLS}/builder_scripts/installer ${BASE_DIR}/installer/installer 2>/dev/null

# Copy BSDInstaller build.conf
cp ${BUILDER_TOOLS}/installer/conf/build.conf \
        ${BASE_DIR}/installer/installer/scripts/build/
# Build BSDInstaller
mkdir -p /usr/ports/packages/All

