#!/bin/sh

#set -e

if [ ! -d "/usr/ports" ]; then
	portsnap fetch
	portsnap extract
fi

(cd /usr/ports/sysutils/cpdup && make install package FORCE_PKG_REGISTER=yo)

CURRENTDIR=`pwd`
[ -r "${CURRENTDIR}/pfsense_local.sh" ] && . ${CURRENTDIR}/pfsense_local.sh

# Update BSDInstaller
echo "Updating BSDInstaller collection..."
cvsup ${CURRENTDIR}/bsdinstaller-supfile

mkdir ${BASE_DIR}/installer
ln -s ${BASE_DIR}/tools/builder_scripts/installer ${BASE_DIR}/installer/installer 2>/dev/null

# Copy BSDInstaller build.conf
cp ${BASE_DIR}/tools/installer/conf/build.conf \
        ${BASE_DIR}/installer/installer/scripts/build/
# Build BSDInstaller
mkdir -p /usr/ports/packages/All

