#!/bin/sh
#
# cvsup_current - part of the pfSense project
#  * Syncs with FreeBSD
#  * Applies pfSense specific patches
#  * Rebuilds pfSense ISO
#

CURRENTDIR=`pwd`
[ -r "${CURRENTDIR}/pfsense_local.sh" ] && . ${CURRENTDIR}/pfsense_local.sh

# Update FreeSBIE2 files from CVS
#cd ../../freesbie2 && cvs update && cd $CURRENTDIR

# These are not needed -- they should be set in pfsense_local.sh
# but just in case . . .
PATCHDIR=${PATCHDIR:-/home/pfsense/tools/patches}
SRCDIR=${SRCDIR:-/usr/src}

# Sanity check
if [ ! -d "${PATCHDIR}" ]; then
	echo "PATCHDIR=${PATCHDIR} is not a directory -- Please fix."
	exit 1
fi

# Sanity check
if [ ! -d "${SRCDIR}" ]; then
	echo "SRCDIR=${SRCDIR} is not a directory -- Please fix."
	exit 1
fi

# Lua BSDInstaller.  Not fully finished.
#rm -rf ${SRCDIR}/sys/boot/*

# CVSUP RELENG_6
cvsup ./stable-supfile

# clog source and usr.sbin/Makefile patch
cd ${SRCDIR}/usr.sbin/
tar xzf ${PATCHDIR}/clog-1.0.1.tar.gz
cd ${SRCDIR}/
patch -p1 < ${PATCHDIR}/clog-makefile.patch

# Traffic shaper fixes for pfctl - loosen anchor checks
cd ${SRCDIR}/contrib/pf/pfctl
patch < ${PATCHDIR}/parse.y

# Making ipfw default to allow all
cd ${SRCDIR}/sys/modules/ipfw
patch < ${PATCHDIR}/ipfw.diff

# Allow ALTQ and VLANS to play nicely
cd ${SRCDIR}/sys/net/
patch < ${PATCHDIR}/altq-vlan.diff

# Crypto fix http://www.freebsd.org/cgi/query-pr.cgi?pr=86598
cd ${SRCDIR}/crypto/openssl/crypto/engine
patch < ${PATCHDIR}/eng_padlock.c.diff

# Fix for BSNMPD
cd ${SRCDIR}/contrib/bsnmp/snmp_mibII/
patch < ${PATCHDIR}/mibII-interfaces.c.diff

cd /usr/src/
patch < ${PATCHDIR}/pf_snmp.patch


# Newest HAL
cd ${SRCDIR}/sys/net80211/
patch < ${PATCHDIR}/net80211.patch

# Newest HAL
cd ${SRCDIR}/sys/dev/ath/
patch < ${PATCHDIR}/ath.patch

# Newest HAL
cd ${SRCDIR}/sys/dev/ath/
patch < ${PATCHDIR}/if_ath.c.diff

# Eliminate the silly error on embedded ro mounts
cd ${SRCDIR}/sys
patch < ${PATCHDIR}/geom_vfs.c.diff

# Turn on extra debugging
cd ${SRCDIR}/sbin/dhclient
patch < ${PATCHDIR}/errwarn.c.diff

# Fixes some Dell PE machines + sata drives
cd ${SRCDIR}/sys/dev/ata/
patch < ${PATCHDIR}/ata-chipset.c.diff

# Newest ATH HAL
cp ${PATCHDIR}/ath_hal-20051212/freebsd/* \
	${SRCDIR}/sys/contrib/dev/ath/freebsd/ 2>/dev/null

# Newest ATH HAL
cp ${PATCHDIR}/ath_hal-20051212/* \
	${SRCDIR}/sys/contrib/dev/ath/ 2>/dev/null

# Newest ATH HAL
cp ${PATCHDIR}/ath_hal-20051212/public/* \
	${SRCDIR}/sys/contrib/dev/ath/public/ 2>/dev/null

# Workaround minor PF issues
cd /usr/src/sys/contrib/pf/net
#patch < ${PATCHDIR}/pf_state_conn.RELENG_6-2.diff

# Fix BSNMD public community string (previously hard coded)
cd /usr/src/contrib/bsnmp/snmpd/
patch < ${PATCHDIR}/bsnmpd-public.diff

echo -n Cleaning up previous build environemnt...Please wait...
cd ${CURRENTDIR}
rm -rf /usr/obj*
echo Done!

echo "Starting pfSense build.  Sit back and have a beer (but not cheap beer)..."

cd ${CURRENTDIR}
./build_iso.sh

