#!/bin/sh
#
# diffgen.sh - a simple script for generating text diffs of pfSense firmware.
#
# NOTE: the patches generated by this application should be applied with -p1.

CATEGORY="Firmware"
DIFFTIME=`cvs -d /cvsroot/ log pfSense/etc/version | grep 'date:' | cut -d ';' -f 1 | head -n 2 | awk '{ print $2, $3 }' | tail -n 1`
NEWVER=`cat pfSense/etc/version`

make_diff() {
	cvs -d /cvsroot/ diff -u -D "$1 $2" pfSense/$3 2> /dev/null >> pfsense_update.patch 
}

echo -n "Deleting old updates... "
rm pfsense_update.patch 2> /dev/null
echo "done."

echo -n "Diffing /etc/*... "
make_diff $DIFFTIME etc/
echo "done."

echo -n "Diffing /usr/local/www/*... "
make_diff $DIFFTIME usr/local/www/
echo "done."

echo -n "Compressing patch... "
tar czf pfSense-Diff-$CATEGORY-Update-$NEWVER.tar pfsense_update.patch
mv pfSense-Diff-$CATEGORY-Update-$NEWVER.tar pfSense-Diff-$CATEGORY-Update-$NEWVER.tgz
echo "done."

echo -n "Cleaning up... "
rm pfsense_update.patch 2> /dev/null
echo "done."
