#!/usr/local/bin/php -c /tmp -q
<?php
/* $Id$ */
/* ========================================================================== */
/*
    pfspkg_installer
    part of pfSense (http://www.pfSense.com)
    Copyright (C) 2007 Daniel S. Haischt <me@daniel.stefan.haischt.name>
    All rights reserved.
                                                                              */
/* ========================================================================== */
/*
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

     1. Redistributions of source code must retain the above copyright notice,
        this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.

    THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
    OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
                                                                              */
/* ========================================================================== */

// currently not being used
$beInteractive = false;
// holds the PHP include path which will be used to search for PHP scripts
$includePath = "";
// holds a file location of a list file. the file contains a comma separated
// list of pfSense package names.
$listFile = "";
// could be either 'config' or 'install'
$mode = "config";

// reads input from stdin
function read() {
  $fp = fopen("/dev/stdin", "r");
  $input = fgets($fp, 255);
  fclose($fp);

  return str_replace("\n", "", $input);
}

// iterate over the cmd line arguments
for ($i = 0; $i < count($argv); $i++) {
	$argument = $argv[$i];
	
	if ($argument == "-i") {
		$beInteractive = true;
	} else if ($argument == "-p") {
		$i++;
		$includePath = $argv[$i];
	} else if ($argument == "-l") {
		$i++;
		$listFile = $argv[$i];
	} else if ($argument == "-m") {
		$i++;
		$mode = $argv[$i];
	}
}

// setup PHP include path if provided
if ($includePath != "") {
        ini_set("include_path", $includePath);
}

// setup package list file interactively
if (! file_exists($listFile) && $mode == "config") {
	require_once("pkg-utils.inc");

	// borrowed from pkg_mgr_install.php	
	$pkg_info = get_pkg_info('all', array('name', 'category', 'website', 'version', 'status', 'descr', 'maintainer', 'required_version'));
	// get package names
	$pkgListA = array_keys($pkg_info);
	// turn names array into a string of comma separated values
	$pkgList = implode(", ", $pkgListA);
	
	print("Available packages:\n");
	print("===================\n");
	print("{$pkgList}\n\n");

	// get the list of packages that should be installed from stdin	
	print("Please provide a comma separated list of packages that should be added to the pfSense installable image:\n");
	// turns the list provided by the user into an array of package names
	$userPkgList = explode(", ", read());
	$saneUserPkgList = array();
	
	// try to figure out whether the user provided package names are correct
	foreach ($userPkgList as $package) {
		if(! in_array($package, $pkgListA)) {
			print("Package is not a pfSense package: {$package}\n");
		} else {
			$saneUserPkgList[] = $package;
		}
	}

	// finally dump the sane list of package names to a file	
	file_put_contents("/usr/local/pfsense-clone/tmp/pkgfile.lst", implode(", ", $saneUserPkgList));
	// copy this script to /usr/local/pfsense-clone/tmp
	copy("pfspkg_installer", "/usr/local/pfsense-clone/tmp/pfspkg_installer");
	// make the script executable
	chmod("/usr/local/pfsense-clone/tmp/pfspkg_installer", 0755);
// package list file already exists
} else if ($mode == "config"){
	// copy existing package list file 
	copy($listFile, "/usr/local/pfsense-clone/tmp/pkgfile.lst");
	// copy this script to /usr/local/pfsense-clone/tmp
	copy("pfspkg_installer", "/usr/local/pfsense-clone/tmp/pfspkg_installer");
	// make the script executable
	chmod("/usr/local/pfsense-clone/tmp/pfspkg_installer", 0755);
}

// install the actual packages using the list file
if (file_exists($listFile) && $mode == "install") {
	require_once("config.inc");
	require_once("pkg-utils.inc");

	// load list of packages
	$pkgList = file_get_contents($listFile);
	// turn list of package names into an array
	$pkgListA = explode(", ", $pkgList);
	
	// iterate over each list element and install the appropriate package
	foreach ($pkgListA as $package) {
		$status = install_package($package);
		
		if($status == -1) {
			print("Installation of {$package} FAILED!\n");
		} else {
			print("Installation of {$package} completed.");
		}
	}
}

?>
