# New ports collection makefile for:	php52-gettext
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/devel/php52-gettext/Makefile,v 1.1 2010/04/23 15:46:00 dinoex Exp $
#

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-gettext

.include "${MASTERDIR}/Makefile"
