# New ports collection makefile for:	php52-xmlwriter
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/textproc/php52-xmlwriter/Makefile,v 1.1 2010/04/23 22:32:38 dinoex Exp $
#

CATEGORIES=	textproc

MASTERDIR=      ${.CURDIR}/../php52

PKGNAMESUFFIX=	-xmlwriter

.include "${MASTERDIR}/Makefile"
