# New ports collection makefile for:	php5-pdo
# Date created:			7 Feb 2007
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/databases/php5-pdo/Makefile,v 1.3 2007/02/09 08:35:34 ale Exp $
#

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../php5

PKGNAMESUFFIX=	-pdo

.include "${MASTERDIR}/Makefile"
