#!/bin/sh
#
#   Launch BSD Installer with fake "installer root"
#   Copyright 2004-2008 Scott Ullrich
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#   
#   1. Redistributions of source code must retain the above copyright notice,
#      this list of conditions and the following disclaimer.
#   
#   2. Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#   
#   THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
#   INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
#   AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
#   AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
#   OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.

product=`cat /etc/inc/globals.inc | grep product_name | cut -d'"' -f4`
factory_shipped_password=`cat /etc/inc/globals.inc | grep factory_shipped_password | cut -d'"' -f4`
factory_shipped_username=`cat /etc/inc/globals.inc | grep factory_shipped_username | cut -d'"' -f4`

echo
echo "Launching ${product} Installer..."
echo
echo "One moment please..."
echo

# Sample running dhcpd command
#ps awwux | grep dhcpd | grep _dhcp | awk '{for(i=11;i<=NF;i++){ printf("%s ", $i) }}' >  /var/run/dhcpd_command
#chmod a+rx /var/run/dhcpd_command 2>/dev/null

#echo "Stopping DHCP server during Installation."
#/usr/bin/killall dhcpd 2>/dev/null 2>&1
/usr/bin/killall syslogd 2>/dev/null 2>&1
rm /var/log/*.log

sysctl kern.geom.debugflags=16

sysctl net.link.ether.inet.log_arp_wrong_iface=0 >/dev/null

/sbin/ifconfig lo0 127.0.0.1/24
/sbin/ifconfig lo0 up

# Check if host is running on VMware
if [ `cat /var/log/dmesg.boot | grep VMware | wc -l` -gt 0 ]; then
		echo -n "VMware detected.  The installer will make changes to tune this host."
        touch /var/IS_VMWARE
		sleep 1
		echo -n "."
		sleep 1
		echo -n "."
		sleep 1
		echo -n "."
		sleep 1
		echo "."
fi

# Check if host is running on pfSenseDEV
if [ `cat /var/log/dmesg.boot | grep pfSense_Dev.6 | wc -l` -gt 0 ]; then
		echo -n "${product} developer iso detected."
        touch /var/pfSenseDEV
		sleep 1
		echo -n "."
		sleep 1
		echo -n "."
		sleep 1
		echo -n "."
		sleep 1
		echo "."
fi

ln -s /var/log/dmesg.boot /var/run/dmesg.boot

echo Launching LUA Installer...
echo -n "LUA_CPATH='/usr/local/lib/lua/5.0/?.so' exec /usr/local/bin/lua50 -l/usr/local/share/lua/5.0/compat-5.1.lua " > /tmp/lua50c51

echo "/usr/local/share/dfuibe_lua/main.lua \
/usr/local/share/dfuibe_lua/conf/BSDInstaller.lua \
/usr/local/share/dfuibe_lua/conf/FreeBSD.lua \
/usr/local/share/dfuibe_lua/conf/pfSense_rescue.lua " >> /tmp/lua50c51

CONSOLE='/usr/bin/tty'
if [ "$CONSOLE" != "/dev/console" ]; then
	/sbin/conscontrol mute on
fi

sh /tmp/lua50c51 >/dev/null 2>&1 &

sleep 1

echo Launching Installer NCurses frontend...
TERM=cons25 && /usr/local/sbin/dfuife_curses

#exec /var/run/dhcpd_command

/sbin/conscontrol mute off

if [ ! -f /tmp/install_complete ]; then
	echo Installation did not finish correctly.
	exit
fi

clear

echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo "${product} is now rebooting"
echo
echo "After the reboot is complete, open a web browser and"
echo "enter http://192.168.1.1 (or the LAN IP Address) in the"
echo "location bar."
echo
echo "*DEFAULT Username*: ${factory_shipped_username}"
echo "*DEFAULT Password*: ${factory_shipped_password}"
echo

echo Rebooting in 5 seconds.  CTRL-C to abort.
sleep 1
echo Rebooting in 4 seconds.  CTRL-C to abort.
sleep 1
echo Rebooting in 3 seconds.  CTRL-C to abort.
sleep 1
echo Rebooting in 2 seconds.  CTRL-C to abort.
sleep 1
echo Rebooting in 1 second..  CTRL-C to abort.
sleep 1
echo
echo ${product} is now rebooting.
echo

reboot

