#!/bin/sh

# Launch BSD Installer with fake "installer root"
# Copyright 2004 BSD Installer Project and the FreeSBIE project
# This file is placed under the BSD license.

echo
echo "Launching pfSense Installer..."
echo
echo "One moment please..."
echo

/usr/bin/killall syslogd 2>/dev/null 2>&1

sysctl kern.geom.debugflags=16
#sysctl kern.geom.label.debug=1
sysctl net.link.ether.inet.log_arp_wrong_iface=0 >/dev/null

/sbin/ifconfig lo0 127.0.0.1/24
/sbin/ifconfig lo0 up

#ln -s /FreeSBIE/tftpdroot /tmp/tftpdroot 2>/dev/null
#echo "Mounting /FreeSBIE/dev..."
#mount_devfs devfs /FreeSBIE/dev

#echo "Mounting /FreeSBIE/usr..."
#MD_LOCAL=`mdconfig -a -t vnode -f /FreeSBIE/uzip/usr.uzip`
#mount -r /dev/$MD_LOCAL.uzip /FreeSBIE/usr

#echo "Mounting /FreeSBIE/var..."
#MD_LOCAL=`mdconfig -a -f /FreeSBIE/uzip/var.uzip`
#mount -r /dev/$MD_LOCAL.uzip /FreeSBIE/var

#mount -t unionfs /.var /FreeSBIE/var

#mkdir -p /FreeSBIE/var/log/
#find / -name dmesg.boot -exec cp {} /FreeSBIE/var/log/ \;

# Let's access this now to prevent the "RockRidge" message
# during the actual install
#ls /FreeSBIE/usr >/dev/null 2>&1
#ls /FreeSBIE/var >/dev/null 2>&1

ln -s /var/log/dmesg.boot /var/run/dmesg.boot

echo Launching LUA Installer...
echo -n "LUA_CPATH='/usr/local/lib/lua/5.0/?.so' exec /usr/local/bin/lua50 -l/usr/local/share/lua/5.0/compat-5.1.lua " > /tmp/lua50c51

echo "/usr/local/share/dfuibe_lua/main.lua \
/usr/local/share/dfuibe_lua/conf/BSDInstaller.lua \
/usr/local/share/dfuibe_lua/conf/FreeBSD.lua \
/usr/local/share/dfuibe_lua/conf/pfSense.lua " >> /tmp/lua50c51
#>/dev/null 2>&1 &" >> /tmp/lua50c51

sh /tmp/lua50c51 >/dev/null 2>&1 &

sleep 1

echo Launching Installer NCurses frontend...
TERM=cons25 && /usr/local/sbin/dfuife_curses

# Check for a failed install and offer to blast logs to developers
#if [ ! -e /tmp/install_complete ]; then
#    echo
#    echo "WARNING!  Installation did not complete as planned."
#    echo
#    echo "Would you like to email the installer logs to the pfSense developers"
#    echo -n "so that they can take a look for obvious errors/bugs [N]? "
#   read ANSWER
#   if [ "${ANSWER}" = "Y" -o "${ANSWER}" = "y" ]; then
#        echo -n "Sending reports, please wait."
#        tar czvpf installer_logs.tgz /tmp/*
#        echo -n "."
#        php /scripts/lua_installer_email_failed_logs.php
#   else
#        echo "Reports are not being sent."
#   fi
#   rm /tmp/install_complete
#fi

/usr/sbin/vidcontrol -S on 2>/dev/null
/usr/sbin/vidcontrol -s 1 2>/dev/null

clear

echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo
echo "pfSense is now rebooting"
echo "After reboot and the console menu is displayed, open a web"
echo "browser and try to surf to the LAN ip address"
echo
echo "The default username and password is admin / pfsense "
echo 

echo Rebooting in 3 seconds.  CTRL-C to abort.
sleep 1
echo Rebooting in 2 seconds.  CTRL-C to abort.
sleep 1
echo Rebooting in 1 second..  CTRL-C to abort.
sleep 1
echo
echo pfSense is now rebooting.

reboot

