# New ports collection makefile for:	php4-mbstring
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/converters/php4-mbstring/Makefile,v 1.1 2004/07/19 07:37:53 ale Exp $
#

CATEGORIES=	converters

MASTERDIR=	/usr/ports/lang/php4

PKGNAMESUFFIX=	-mbstring

.include "${MASTERDIR}/Makefile"
