# New ports collection makefile for:	php5-mbstring
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/converters/php5-mbstring/Makefile,v 1.1 2004/07/19 08:46:12 ale Exp $
#

CATEGORIES=	converters

MASTERDIR=	${.CURDIR}/../php5

PKGNAMESUFFIX=	-mbstring

.include "${MASTERDIR}/Makefile"
