# New ports collection makefile for:	php4-curl
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/ftp/php4-curl/Makefile,v 1.3 2007/02/17 10:19:17 ale Exp $
#

CATEGORIES=	ftp

MASTERDIR=	/usr/ports/lang/php4

PKGNAMESUFFIX=	-curl

.include "${MASTERDIR}/Makefile"
