# New ports collection makefile for:	php4-ctype
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/textproc/php4-ctype/Makefile,v 1.1 2004/07/19 08:33:33 ale Exp $
#

CATEGORIES=	textproc

MASTERDIR=	/usr/ports/lang/php4

PKGNAMESUFFIX=	-ctype

.include "${MASTERDIR}/Makefile"
