#!/bin/sh
# $FreeBSD: ports/net/openntpd/pkg-install,v 1.1 2004/07/11 17:18:23 naddy Exp $
#

if [ "$2" != "PRE-INSTALL" ]; then
	exit 0
fi

USER=_ntp
GROUP=${USER}
UID=123
GID=${UID}

if ! pw groupshow "${GROUP}" 2>/dev/null 1>&2; then
	if pw groupadd ${GROUP} -g ${GID}; then
		echo "Added group \"${GROUP}\"."
	else
		echo "Adding group \"${GROUP}\" failed..."
		exit 1
	fi
fi

if ! pw usershow "${USER}" 2>/dev/null 1>&2; then
	if pw useradd ${USER} -u ${UID} -g ${GROUP} -h - \
		-s "/sbin/nologin" -d "/var/empty" \
		-c "NTP daemon"; \
	then
		echo "Added user \"${USER}\"."
	else
		echo "Adding user \"${USER}\" failed..."
		exit 1
	fi
fi

exit 0
