# New ports collection makefile for:	php4-bz2
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/archivers/php4-bz2/Makefile,v 1.1 2004/07/19 07:34:57 ale Exp $
#

CATEGORIES=	archivers

MASTERDIR=	${.CURDIR}/../../lang/php4

PKGNAMESUFFIX=	-bz2

.include "${MASTERDIR}/Makefile"
