# $FreeBSD: ports/net/relayd/files/Makefile.relayctl,v 1.1 2010/05/28 11:59:49 mm Exp $

PROG=	relayctl

.PATH:	${.CURDIR}/../relayd
SRCS=	buffer.c \
	imsg.c \
	log.c

.PATH:	${.CURDIR}
SRCS+=	relayctl.c \
	parser.c

MAN=	relayctl.8

CFLAGS+=	-D__dead=''
CFLAGS+=	-I${.CURDIR} \
		-I${.CURDIR}/../relayd \
		-I${PREFIX}/include

.include <bsd.prog.mk>
