# New ports collection makefile for:	php52-xmlreader
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/textproc/php52-xmlreader/Makefile,v 1.1 2010/04/23 22:31:51 dinoex Exp $
#

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-xmlreader

.include "${MASTERDIR}/Makefile"
