# Ports collection makefile for:	isc-dhcp42-client
# Date created:				29 June 2011
# Whom:					Ryan Steinmetz <rpsfa@rit.edu>
#
# $FreeBSD: head/net/isc-dhcp42-client/Makefile 300897 2012-07-14 14:29:18Z beat $
#

COMMENT=	The ISC Dynamic Host Configuration Protocol client

SUBSYS=		client
MASTERDIR=	${.CURDIR}/../isc-dhcp42-server

.include "${MASTERDIR}/Makefile"
