# Ports collection makefile for:    isc-dhcp42-relay
# Date created:         28 March 2010
# Whom:                 Wesley Shields <wxs@FreeBSD.org>
#
# $FreeBSD: ports/net/isc-dhcp42-relay/Makefile,v 1.1 2010/05/06 20:24:00 wxs Exp $
#

COMMENT=	The ISC Dynamic Host Configuration Protocol client

SUBSYS=		relay
MASTERDIR=	${.CURDIR}/../isc-dhcp42-client

.include "${MASTERDIR}/Makefile"
