# New ports collection makefile for:	php4-openssl
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/security/php4-openssl/Makefile,v 1.1 2004/07/19 08:31:10 ale Exp $
#

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php4

PKGNAMESUFFIX=	-openssl

.include "${MASTERDIR}/Makefile"
