# New ports collection makefile for:	php4-pcntl
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/devel/php4-pcntl/Makefile,v 1.1 2004/07/19 08:01:07 ale Exp $
#

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../php4

PKGNAMESUFFIX=	-pcntl

.include "${MASTERDIR}/Makefile"
