# ex:ts=8
# Ports collection makefile for:    dhcp
# Date created:         28 April 2003
# Whom:                 cyrille.lefevre@laposte.net
#
# $FreeBSD: ports/net/isc-dhcp30-relay/Makefile,v 1.4 2008/10/13 11:10:11 edwin Exp $
#

COMMENT=	The ISC Dynamic Host Configuration Protocol relay

# Local variables
#

SUBSYS=		relay

# Local overrides
#

MASTERDIR=	${.CURDIR}/../isc-dhcp30-server

.include "${MASTERDIR}/Makefile"
