# New ports collection makefile for:	php4-readline
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/devel/php4-readline/Makefile,v 1.1 2004/07/19 08:01:35 ale Exp $
#

CATEGORIES=	devel

MASTERDIR=	/usr/ports/lang/php4

PKGNAMESUFFIX=	-readline

.include "${MASTERDIR}/Makefile"
