# New ports collection makefile for:	php5-shmop
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/devel/php5-shmop/Makefile,v 1.1 2004/07/19 09:04:37 ale Exp $
#

CATEGORIES=	devel

MASTERDIR=	/usr/ports/lang/php5

PKGNAMESUFFIX=	-shmop

.include "${MASTERDIR}/Makefile"
