#!/bin/sh
echo "Warning, this doesn't really work well"
exit
cd /home/${USER}/conversion

. lib.inc

# Overrides 
CVSMODULE=pfSense
GITDST=git@rcs.pfsense.org:pfsense-import-test-minus-binaries/mainline.git


sync_from_cvs
purge_repo
cvs_to_git
update_pfSense_gitorious
