# New ports collection makefile for:	php52-xml
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/textproc/php52-xml/Makefile,v 1.1 2010/04/23 22:30:46 dinoex Exp $
#

CATEGORIES=	textproc

MASTERDIR=      ${.CURDIR}/../php52-pfsense

PKGNAMESUFFIX=	-xml

.include "${MASTERDIR}/Makefile"
