# New ports collection makefile for:	php52-ldap
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/net/php52-ldap/Makefile,v 1.1 2010/04/23 15:59:24 dinoex Exp $
#

CATEGORIES=	net

MASTERDIR=      ${.CURDIR}/../php52

PKGNAMESUFFIX=	-ldap

.include "${MASTERDIR}/Makefile"
