# New ports collection makefile for:	php52-bz2
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/archivers/php52-bz2/Makefile,v 1.1 2010/04/23 15:16:12 dinoex Exp $
#

CATEGORIES=	archivers

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-bz2

.include "${MASTERDIR}/Makefile"
