# New ports collection makefile for:	php52-sysvmsg
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/devel/php52-sysvmsg/Makefile,v 1.1 2010/04/23 22:27:15 dinoex Exp $
#

CATEGORIES=	devel

MASTERDIR=      ${.CURDIR}/../php52

PKGNAMESUFFIX=	-sysvmsg

.include "${MASTERDIR}/Makefile"
