# New ports collection makefile for:	php52-pgsql
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/databases/php52-pgsql/Makefile,v 1.1 2010/04/23 16:31:42 dinoex Exp $
#

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-pgsql

.include "${MASTERDIR}/Makefile"
