#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/lpd,v 1.8.4.1 2008/01/28 07:58:31 dougb Exp $
#

# PROVIDE: igmpproxy
# REQUIRE: NETWORKING

. /etc/rc.subr

name="igmpproxy"
rcvar=`set_rcvar`
command="/usr/local/sbin/${name}"
required_files="/usr/local/etc/igmpproxy.conf"
igmpproxy_enable=${igmpproxy_enable-"NO"}

load_rc_config $name
run_rc_command "$1"
