#!/bin/sh
#
# $FreeBSD: ports/net/isc-dhcp31-server/pkg-install,v 1.3 2006/08/27 16:04:02 sem Exp $
#

[ $# != 2 ] && exit 1
[ -z "${PKG_PREFIX}" ] && exit 1
[ -n "${BATCH}" ] && exit 0

case $2 in
POST-INSTALL)
	if [ -x ${PKG_PREFIX}/etc/rc.d/isc-dhcpd ]; then
		${PKG_PREFIX}/etc/rc.d/isc-dhcpd forceinstall
	else
		${PKG_PREFIX}/etc/rc.d/isc-dhcpd.sh forceinstall
	fi
	;;
DEINSTALL)
	if [ -x ${PKG_PREFIX}/etc/rc.d/isc-dhcpd ]; then
		${PKG_PREFIX}/etc/rc.d/isc-dhcpd forceuninstall
	else
		${PKG_PREFIX}/etc/rc.d/isc-dhcpd.sh forceuninstall
	fi
	;;
POST-DEINSTALL|PRE-INSTALL)
	;;
*)
	echo "usage: $0 <PKG_NAME> {PRE-INSTALL|POST-INSTALL|DEINSTALL|POST-DEINSTALL}" >&2
	exit 1
	;;
esac
