# New ports collection makefile for:	php5-gmp
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/math/php5-gmp/Makefile,v 1.5 2010/07/27 15:13:53 ale Exp $
#

CATEGORIES=	math

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-gmp

.include "${MASTERDIR}/Makefile"
