# ex:ts=8
# Ports collection makefile for:    dhcp
# Date created:         28 April 2003
# Whom:                 cyrille.lefevre@laposte.net
#
# $FreeBSD: ports/net/isc-dhcp3-relay/Makefile,v 1.2 2005/06/09 18:56:58 sem Exp $
#

COMMENT=	The ISC Dynamic Host Configuration Protocol relay

# Local variables
#

SUBSYS=		relay

# Local overrides
#

MASTERDIR=	${.CURDIR}/../isc-dhcp3-server

.include "${MASTERDIR}/Makefile"
