# New ports collection makefile for:	php4-zlib
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/archivers/php4-zlib/Makefile,v 1.1 2004/07/19 07:36:23 ale Exp $
#

CATEGORIES=	archivers

MASTERDIR=	/usr/ports/lang/php4

PKGNAMESUFFIX=	-zlib

.include "${MASTERDIR}/Makefile"
