# New ports collection makefile for:	php52-sockets
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/net/php52-sockets/Makefile,v 1.1 2010/04/23 22:19:56 dinoex Exp $
#

CATEGORIES=	net

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-sockets

.include "${MASTERDIR}/Makefile"
