# New ports collection makefile for:	php52-mysql
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/databases/php52-mysql/Makefile,v 1.1 2010/04/23 16:10:11 dinoex Exp $
#

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-mysql

.include "${MASTERDIR}/Makefile"
