#
#  pfSense pfPorts
#
#  This directory holds port structures for common pfSense items
#  such as add on programs and the base system itself.
#
#  To build pfSense simply type make in this directory.
#

SUBDIR += ftpsesame
SUBDIR += atareinit
SUBDIR += grub
SUBDIR += cpdup
SUBDIR += beep
SUBDIR += check_reload_status
SUBDIR += choparp
SUBDIR += dnsmasq
SUBDIR += expiretable
SUBDIR += ifstated
SUBDIR += ipsec-tools
SUBDIR += isc-dhcp3-relay
SUBDIR += isc-dhcp3-server
SUBDIR += lighttpd
SUBDIR += minicron
SUBDIR += miniupnpd
SUBDIR += mpd4
#SUBDIR += olsrd
SUBDIR += pftop
SUBDIR += libevent
SUBDIR += pftpx
#SUBDIR += rrdtool
SUBDIR += relayd
SUBDIR += slbd
SUBDIR += ssh_tunnel_shell
SUBDIR += sshlockout_pf
SUBDIR += stats
SUBDIR += vtsh
SUBDIR += pftpx
SUBDIR += php5
SUBDIR += php5-gettext
SUBDIR += php5-readline
SUBDIR += pecl-APC
SUBDIR += pecl-radius
SUBDIR += php5-pcre
SUBDIR += openvpn
SUBDIR += zip
SUBDIR += links
SUBDIR += dnswatch
SUBDIR += verifysig
PORTSTOP=       yes

.include <bsd.port.subdir.mk>

