# New ports collection makefile for:	php52-simplexml
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/textproc/php52-simplexml/Makefile,v 1.1 2010/04/23 22:16:04 dinoex Exp $
#

CATEGORIES=	textproc

MASTERDIR=      ${.CURDIR}/../php52

PKGNAMESUFFIX=	-simplexml

.include "${MASTERDIR}/Makefile"
