# New ports collection makefile for:	php4-posix
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/sysutils/php4-posix/Makefile,v 1.1 2004/07/19 08:32:34 ale Exp $
#

CATEGORIES=	sysutils

MASTERDIR=	${.CURDIR}/../php4

PKGNAMESUFFIX=	-posix

.include "${MASTERDIR}/Makefile"
