# New ports collection makefile for:	php4-ldap
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/net/php4-ldap/Makefile,v 1.1 2004/07/19 08:24:07 ale Exp $
#

CATEGORIES=	net

MASTERDIR=	${.CURDIR}/../../lang/php4

PKGNAMESUFFIX=	-ldap

.include "${MASTERDIR}/Makefile"
