# New ports collection makefile for:	choparp
# Date created:		7 October 1997
# Whom:			itojun@itojun.org
#
# $FreeBSD: ports/net-mgmt/choparp/Makefile,v 1.17 2010/05/04 14:03:13 nork Exp $
#

PORTNAME=	choparp
PORTVERSION=	20021107
PORTREVISION=	4
CATEGORIES=	net-mgmt
MASTER_SITES=	SF

MAINTAINER=	nork@FreeBSD.org
COMMENT=	Simple proxy arp daemon

USE_RC_SUBR=	choparp.sh

MANCOMPRESSED=	yes
MAN8=		choparp.8
PLIST_FILES=	sbin/choparp

.include <bsd.port.mk>
