# New ports collection makefile for:	php52-sqlite
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/databases/php52-sqlite/Makefile,v 1.1 2010/04/23 22:21:56 dinoex Exp $
#

CATEGORIES=	databases

MASTERDIR=      ${.CURDIR}/../php52

PKGNAMESUFFIX=	-sqlite

.include "${MASTERDIR}/Makefile"
