# New ports collection makefile for:	php5-curl
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/ftp/php5-curl/Makefile,v 1.3 2007/03/11 21:57:26 ale Exp $
#

CATEGORIES=	ftp

MASTERDIR=	/usr/ports/lang/php5

PKGNAMESUFFIX=	-curl

.include "${MASTERDIR}/Makefile"
