# New ports collection makefile for:	php52-shmop
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/devel/php52-shmop/Makefile,v 1.1 2010/04/23 22:14:45 dinoex Exp $
#

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-shmop

.include "${MASTERDIR}/Makefile"
