# New ports collection makefile for:	php52-pcre
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/devel/php52-pcre/Makefile,v 1.1 2010/04/23 15:09:07 dinoex Exp $
#

CATEGORIES=	devel

MASTERDIR=      ${.CURDIR}/../php52

PKGNAMESUFFIX=	-pcre

.include "${MASTERDIR}/Makefile"
