# New ports collection makefile for:    php53-openssl
# Date created:                 12 Apr 2012
# Whom:                         Florian Smeets <flo@FreeBSD.org>
#
# $FreeBSD: ports/security/php53-openssl/Makefile,v 1.1 2012/05/16 09:46:49 flo Exp $
#

CATEGORIES=     security

MASTERDIR=      ${.CURDIR}/../../lang/php53

PKGNAMESUFFIX=  -openssl

.include "${MASTERDIR}/Makefile"