# New ports collection makefile for:	php52-ctype
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/textproc/php52-ctype/Makefile,v 1.1 2010/04/23 15:21:26 dinoex Exp $
#

CATEGORIES=	textproc

MASTERDIR=      ${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-ctype

.include "${MASTERDIR}/Makefile"
