# New ports collection makefile for:	imspector
# Date created:		02 December 2006
# Whom:			Ryan Wagoner (ryan@wgnrs.dynu.com)
#
# $FreeBSD: $

PORTNAME=		imspector
PORTVERSION=	0.3
CATEGORIES=		net
MASTER_SITES=	http://www.imspector.org/downloads/
DISTFILES=		imspector-0.3.tar.gz

LIB_DEPENDS=	mysqlclient.15:${PORTSDIR}/databases/mysql51-client

MAINTAINER=		ryan@wgnrs.dynu.com
COMMENT=		Instant Messenger transparent proxy with logging capabilities

.include <bsd.port.mk>
