# New ports collection makefile for:	php5-pdo_sqlite
# Date created:			7 Feb 2007
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/databases/php5-pdo_sqlite/Makefile,v 1.1 2007/02/09 08:36:39 ale Exp $
#

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-pdo_sqlite

.include "${MASTERDIR}/Makefile"
