# New ports collection makefile for:	php4-sysvsem
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/devel/php4-sysvsem/Makefile,v 1.1 2004/07/19 08:02:56 ale Exp $
#

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php4

PKGNAMESUFFIX=	-sysvsem

.include "${MASTERDIR}/Makefile"
