# New ports collection makefile for:	php4-tokenizer
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/devel/php4-tokenizer/Makefile,v 1.1 2004/07/19 08:03:55 ale Exp $
#

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php4

PKGNAMESUFFIX=	-tokenizer

.include "${MASTERDIR}/Makefile"
