# New ports collection makefile for:	php52-posix
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/sysutils/php52-posix/Makefile,v 1.1 2010/04/23 16:34:38 dinoex Exp $
#

CATEGORIES=	sysutils

MASTERDIR=      ${.CURDIR}/../php52

PKGNAMESUFFIX=	-posix

.include "${MASTERDIR}/Makefile"
