# New ports collection makefile for:	php52-openssl
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/security/php52-openssl/Makefile,v 1.1 2010/04/23 16:19:33 dinoex Exp $
#

CATEGORIES=	security

MASTERDIR=      ${.CURDIR}/../php52

PKGNAMESUFFIX=	-openssl

.include "${MASTERDIR}/Makefile"
