Index: Makefile
===================================================================
RCS file: /home/ncvs/src/sys/modules/Makefile,v
retrieving revision 1.540.2.5.2.1
diff -u -r1.540.2.5.2.1 Makefile
--- Makefile	6 Feb 2008 03:24:27 -0000	1.540.2.5.2.1
+++ Makefile	23 Jun 2008 23:58:02 -0000
@@ -89,6 +89,7 @@
 	fxp \
 	gem \
 	geom \
+	glxsb \
 	${_harp} \
 	hatm \
 	${_hfa} \
