# Ports collection makefile for:    isc-dhcp41-relay
# Date created:         28 March 2010
# Whom:                 Wesley Shields <wxs@FreeBSD.org>
#
# $FreeBSD: ports/net/isc-dhcp41-relay/Makefile,v 1.1 2010/05/06 20:24:00 wxs Exp $
#

COMMENT=	The ISC Dynamic Host Configuration Protocol relay

SUBSYS=		relay
MASTERDIR=	${.CURDIR}/../isc-dhcp41-server

.include "${MASTERDIR}/Makefile"
