# New ports collection makefile for:	php52-sysvshm
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/devel/php52-sysvshm/Makefile,v 1.1 2010/04/23 22:29:25 dinoex Exp $
#

CATEGORIES=	devel

MASTERDIR=      ${.CURDIR}/../php52

PKGNAMESUFFIX=	-sysvshm

.include "${MASTERDIR}/Makefile"
