# New ports collection makefile for:	php5-ctype
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/textproc/php5-ctype/Makefile,v 1.1 2004/07/19 09:21:05 ale Exp $
#

CATEGORIES=	textproc

MASTERDIR=	/usr/ports/lang/php5

PKGNAMESUFFIX=	-ctype

.include "${MASTERDIR}/Makefile"
