# New ports collection makefile for:	php52-spl
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/devel/php52-spl/Makefile,v 1.1 2010/04/23 22:21:09 dinoex Exp $
#

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-spl

.include "${MASTERDIR}/Makefile"
