PORTNAME=		ipfw-classifyd
PORTVERSION=		0.1
CATEGORIES=		net
MASTER_SITES=		http://people.freebsd.org/~mtm/
DISTFILES=		ipfw-classifyd.tar.bz2

MAINTAINER=		ermal@pfsense.com
COMMENT=		application classifier

post-extract:
	mv work/ipfw-classifyd work/ipfw-classifyd-0.1
.include <bsd.port.mk>

clean:
	echo
