PORTNAME=		ipfw-classifyd
PORTVERSION=		0.1
CATEGORIES=		net
MASTER_SITES=		#
DISTFILES=		#
NO_STAGE=	yes

MAINTAINER=		ermal@pfsense.com
COMMENT=		application classifier

extract:
	mkdir -p ${WRKSRC}
	cp files/* ${WRKSRC}

.include <bsd.port.mk>
