# New ports collection makefile for:	php5-sysvsem
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/devel/php5-sysvsem/Makefile,v 1.1 2004/07/19 09:07:17 ale Exp $
#

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../php5

PKGNAMESUFFIX=	-sysvsem

.include "${MASTERDIR}/Makefile"
