# New ports collection makefile for:	php5-pcre
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/devel/php5-pcre/Makefile,v 1.4 2007/05/20 08:27:29 ale Exp $
#

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-pcre

.include "${MASTERDIR}/Makefile"
