# New ports collection makefile for:	php52-pcntl
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/devel/php52-pcntl/Makefile,v 1.1 2010/04/23 16:21:08 dinoex Exp $
#

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-pcntl

.include "${MASTERDIR}/Makefile"
