# New ports collection makefile for:	php52-json
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/devel/php52-json/Makefile,v 1.1 2010/04/23 15:58:00 dinoex Exp $
#

CATEGORIES=	devel

MASTERDIR=     ${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-json

.include "${MASTERDIR}/Makefile"
