# New ports collection makefile for:	php52-curl
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/ftp/php52-curl/Makefile,v 1.1 2010/04/23 15:28:15 dinoex Exp $
#

CATEGORIES=	ftp

MASTERDIR=      ${.CURDIR}/../php52

PKGNAMESUFFIX=	-curl

.include "${MASTERDIR}/Makefile"
