# New ports collection makefile for:	php52-mbstring
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/converters/php52-mbstring/Makefile,v 1.1 2010/04/23 16:01:25 dinoex Exp $
#

CATEGORIES=	converters

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-mbstring

.include "${MASTERDIR}/Makefile"
