# New ports collection makefile for:	php52-bcmath
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/math/php52-bcmath/Makefile,v 1.1 2010/04/23 15:13:13 dinoex Exp $
#

CATEGORIES=	math

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-bcmath

.include "${MASTERDIR}/Makefile"
