# New ports collection makefile for:	php4-bcmath
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/math/php4-bcmath/Makefile,v 1.1 2004/07/19 08:15:50 ale Exp $
#

CATEGORIES=	math

MASTERDIR=	${.CURDIR}/../../lang/php4

PKGNAMESUFFIX=	-bcmath

.include "${MASTERDIR}/Makefile"
