# New ports collection makefile for:	php52-tokenizer
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/devel/php52-tokenizer/Makefile,v 1.1 2010/04/23 22:25:27 dinoex Exp $
#

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-tokenizer

.include "${MASTERDIR}/Makefile"
