# New ports collection makefile for:	php5-sysvshm
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/devel/php5-sysvshm/Makefile,v 1.1 2004/07/19 09:07:44 ale Exp $
#

CATEGORIES=	devel

MASTERDIR=	/usr/ports/lang/php5

PKGNAMESUFFIX=	-sysvshm

.include "${MASTERDIR}/Makefile"
