# New ports collection makefile for:	php52-mhash
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/security/php52-mhash/Makefile,v 1.1 2010/04/23 16:05:08 dinoex Exp $
#

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-mhash

.include "${MASTERDIR}/Makefile"
