# New ports collection makefile for:	php4
# Date created:				Tue Feb 18 11:17:13 CET 2003
# Whom:					Alex Dupre <sysadmin@alexdupre.com>
#
# $FreeBSD: ports/lang/php4/Makefile,v 1.88 2005/07/13 19:56:27 ale Exp $
#

PORTNAME=	pfsense-lite
PORTVERSION=	0.0.2
PORTREVISION?=	0
CATEGORIES?=	sysutils
MASTER_SITES=	# empty
DISTFILES=	# none
EXTRACT_ONLY=	# empty

MAINTAINER?=	jebc@c4solutions.net
COMMENT?=	reinits ata channel 0

WHERE=		bin
PLIST_FILES=    ${WHERE}/${PORTNAME}

RUN_DEPENDS+=	blah:${PORTSDIR}/pfPorts/blah

NO_BUILD=	yes

.include <bsd.port.mk>
