# New ports collection makefile for:	php5-pcntl
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/devel/php5-pcntl/Makefile,v 1.1 2004/07/19 09:03:40 ale Exp $
#

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../php5

PKGNAMESUFFIX=	-pcntl

.include "${MASTERDIR}/Makefile"
