# New ports collection makefile for:	php5-json
# Date created:			10 Dec 2008
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/devel/php5-json/Makefile,v 1.3 2008/12/11 08:54:19 ale Exp $
#

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php5

PKGNAMESUFFIX=	-json

.include "${MASTERDIR}/Makefile"
