# New ports collection makefile for:	php52-zlib
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/archivers/php52-zlib/Makefile,v 1.1 2010/04/23 22:34:59 dinoex Exp $
#

CATEGORIES=	archivers

MASTERDIR=	${.CURDIR}/../../lang/php52

PKGNAMESUFFIX=	-zlib

.include "${MASTERDIR}/Makefile"
