# New ports collection makefile for:	php52-readline
# Date created:			17 Apr 2010
# Whom:				Alex Keda <admin@lissyara.su>
#
# $FreeBSD: ports/devel/php52-readline/Makefile,v 1.1 2010/04/23 22:10:37 dinoex Exp $
#

CATEGORIES=	devel

MASTERDIR=      ${.CURDIR}/../php52

PKGNAMESUFFIX=	-readline

.include "${MASTERDIR}/Makefile"
