# New ports collection makefile for:	php4-xml
# Date created:			7 Jul 2004
# Whom:				Alex Dupre <ale@FreeBSD.org>
#
# $FreeBSD: ports/textproc/php4-xml/Makefile,v 1.1 2004/07/19 07:10:38 ale Exp $
#

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php4

PKGNAMESUFFIX=	-xml

.include "${MASTERDIR}/Makefile"
